# Configuración
@api = http://localhost:3000/api
@id_pelicula = 69a1a2c7fb349fdfe0235954

# Crear película
POST http://localhost:3000/api/movie
Content-Type: application/json

{
  "title": "si",
  "director": "si",
  "year": 1354,
  "genre": "horror",
  "copies": 5
}

# 2. Obtener todas las películas 
GET {{api}}/movie

# 3. Filtrar por género 
GET {{api}}/movie?genre=horror

# 4. Buscar por título 
GET {{api}}/movie?search=fic

# 5. Alquilar una película 
# Decrementa availableCopies e incrementa timesRented
POST {{api}}/movie/{{id_pelicula}}/rent

# 6. Devolver una película 
# Incrementa availableCopies
POST {{api}}/movie/{{id_pelicula}}/return

# 7. Ver Top 5 más alquiladas 
GET {{api}}/movie/stats/top

# 8. Subir carátula 
# Se necesita tener una imagen llamada 'poster.jpg' en la misma carpeta que este archivo .http
PATCH {{api}}/movie/{{id_pelicula}}/cover
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="cover"; filename="poster.jpg"
Content-Type: image/jpeg

< ./poster.jpg
--boundary--

# 9. Obtener la imagen de la carátula 
GET {{api}}/movie/{{id_pelicula}}/cover

# 10. Eliminar película 
# Esto también debería borrar el archivo físico en /storage
DELETE {{api}}/movie/{{id_pelicula}}