### Configuración
@api = http://localhost:3000/api
@id_pelicula = 69a1917156cf937f64f16bb7

### Crear película
POST http://localhost:3000/api/movie
Content-Type: application/json

{
  "title": "Pulpo",
  "director": "Quedddd",
  "year": 1954,
  "genre": "pop",
  "copies": 5
}

### 2. Obtener todas las películas (GET)
GET {{api}}/movie

### 3. Filtrar por género (GET)
GET {{api}}/movie?genre=action

### 4. Buscar por título (GET - Bonus)
GET {{api}}/movie?search=pulp

### 5. Alquilar una película (POST)
# Decrementa availableCopies e incrementa timesRented
POST {{api}}/movie/{{id_pelicula}}/rent

### 6. Devolver una película (POST)
# Incrementa availableCopies
POST {{api}}/movie/{{id_pelicula}}/return

### 7. Ver Top 5 más alquiladas (GET)
GET {{api}}/movie/stats/top

### 8. Subir carátula (PATCH)
# Nota: Necesitas tener una imagen llamada 'poster.jpg' en la misma carpeta que este archivo .http
# O usar Postman/Insomnia si el REST Client te da problemas con multipart
PATCH {{api}}/movie/{{id_pelicula}}/cover
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="cover"; filename="poster.jpg"
Content-Type: image/jpeg

< ./poster.jpg
--boundary--

### 9. Obtener la imagen de la carátula (GET)
GET {{api}}/movie/{{id_pelicula}}/cover

### 10. Eliminar película (DELETE)
# Esto también debería borrar el archivo físico en /storage
DELETE {{api}}/movie/{{id_pelicula}}